spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: ticket-alpha
          uri: lb://ticket-alpha
          predicates:
            - Path=/api/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://server1:8761/eureka,http://server2:8762/eureka,http://server3:8763/eureka


management:
  endpoints:
    web:
      exposure:
        include: "*"