spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: ticket-alpha
          uri: lb://ticket-alpha
          predicates:
            - Path=/api/**
        - id: ticket-service
          uri: lb://ticket-service
          predicates:
            - Path=/tickets/**
      default-filters:
        - name: Retry
          args:
            retires: 3
            methods: GET,POST,PUT
            statuses: INTERNAL_SERVER_ERROR,BAD_GATEWAY
            backoff:
              firstBackoff: 50ms
              maxBackOff: 500ms
              factor: 2
              basedOnPreviousValue: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://server1:8761/eureka,http://server2:8762/eureka,http://server3:8763/eureka


management:
  endpoints:
    web:
      exposure:
        include: "*"